In [1]:
import numpy as np
x = np.array([1, 2, 3])
x.reshape((1, 3)) 

array([[1, 2, 3]])

In [2]:
x[np.newaxis, :] 

array([[1, 2, 3]])

In [3]:
x.reshape((3, 1))


array([[1],
       [2],
       [3]])

In [4]:
x[:,np.newaxis]


array([[1],
       [2],
       [3]])

In [5]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
np.concatenate([x,y])


array([1, 2, 3, 4, 5, 6])

In [6]:
a = np.array([[1, 2],
 [3, 4]])
b = np.array([[5, 6],
 [7, 8]])
# Kết hợp theo chiều đầu tiên (trục dọc/ trục 0) của mảng
c = np.concatenate((a, b))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7]:
d = np.concatenate([a, b], axis=1)
print(d)

[[1 2 5 6]
 [3 4 7 8]]


In [10]:
import numpy as np
arr = np.arange(10)
sub_arr1=np.split(arr,[3, 6])
sub_arr2=np.split(arr,2)
print("Mảng con sub_arr1 là:", sub_arr1, "\n")
print("Mảng con sub_arr2 là:", sub_arr2)

Mảng con sub_arr1 là: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])] 

Mảng con sub_arr2 là: [array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [11]:
arr = np.arange(16).reshape((4,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
upper,lower = np.vsplit(arr,2) #Tách theo trục ngang
print("Kết quả sau khi tách từ mảng ban đầu \n")
print(upper,"\n")
print(lower,"\n")

Kết quả sau khi tách từ mảng ban đầu 

[[0 1 2 3]
 [4 5 6 7]] 

[[ 8  9 10 11]
 [12 13 14 15]] 



In [13]:
left,right=np.hsplit(arr,2)
print("Kết quả sau khi tách từ mảng ban đầu \n")
print(left,"\n")
print(right,"\n")

Kết quả sau khi tách từ mảng ban đầu 

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]] 



In [15]:
arr = np.array([1, 2, 3, 4, 5])
new_element = 10
index_to_insert = 2
new_arr = np.insert(arr, index_to_insert, new_element)
print(new_arr)

[ 1  2 10  3  4  5]


In [16]:
arr_2d = np.array([[1, 2], [3, 4], [5, 6]])
new_element = [7, 8]
row_to_insert = 1
new_arr_2d=np.insert(arr_2d,row_to_insert,new_element,axis=0)
print(new_arr_2d)

[[1 2]
 [7 8]
 [3 4]
 [5 6]]


In [17]:
import numpy as np
arr=np.array([1,2,3])
new_arr=np.append(arr,4)
print(arr)
print(new_arr)

[1 2 3]
[1 2 3 4]


In [18]:
arr = np.array([1, 5, 2, 3, 4])
max_idx = np.argmax(arr)
min_idx = np.argmin(arr)
print(max_idx)
print(min_idx)

1
0


In [20]:
arr = np.array([1, 2, 3, 4, 5])
imdices = np.argwhere(arr)
imdices

array([[0],
       [1],
       [2],
       [3],
       [4]], dtype=int64)

In [21]:
arr = np.array([1, 2, 3, 4, 5])
sorted_arr = np.sort(arr)
sorted_arr

array([1, 2, 3, 4, 5])

In [22]:
arr = np.array([1, 2, 3, 4, 5])
arr.sort()
arr

array([1, 2, 3, 4, 5])

In [6]:
import numpy as np
arr = np.array([3, 1, 4, 2, 5])
sorted_arr_descending= np.sort(arr)[::-1]
sorted_arr_descending

array([5, 4, 3, 2, 1])

In [7]:
arr = np.array([3, 1, 4, 2, 5])
sorted_arr_descending= np.sort(arr)[::-1]
sorted_arr_descending

array([5, 4, 3, 2, 1])

In [8]:
arr = np.array([3, 1, 4, 2, 5])
idx_to_delete = 2
new_arr=np.delete(arr,idx_to_delete)
new_arr

array([3, 1, 2, 5])

In [9]:
arr = np.array([3, 1, 4, 2, 5])
idx_to_delete = [1, 3]
new_arr = np.delete(arr, idx_to_delete)
new_arr

array([3, 4, 5])

In [11]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_idx_to_delete = 1
new_arr_2d = np.delete(arr_2d, row_idx_to_delete, axis=0)
new_arr_2d

array([[1, 2, 3],
       [7, 8, 9]])

In [12]:
arr = np.array([1, 2, 3, 4, 5])
del arr
arr

NameError: name 'arr' is not defined

In [13]:
arr = np.array([1, 2, 3, 4, 5])
arr = None
print(arr)

None


In [14]:
import numpy as np

dtype = [('name', 'U20'), ('age', int), ('height', float)]

data = np.array([('Minh', 22, 165.5),
    ('Lan', 40, 160.0),
    ('Linh', 31, 165.0),
    ('Lương',18,166.5),
    ('Thanh',50, 170.0)], dtype=dtype)
print(data)
print(data.dtype)

[('Minh', 22, 165.5) ('Lan', 40, 160. ) ('Linh', 31, 165. )
 ('Lương', 18, 166.5) ('Thanh', 50, 170. )]
[('name', '<U20'), ('age', '<i4'), ('height', '<f8')]


In [16]:
import numpy as np
import time

arr = np.arange(100000000, dtype=np.int64)

start_time = time.time()
total = np.int64(0)
for num in arr:
 total += num
end_time = time.time()
elapsed_time_loop = end_time - start_time
print("Tổng các phần tử mảng arr khi sử dụng vòng lặp:", total) 
print("Thời gian (giây) khi sử dụng vòng lặp:", elapsed_time_loop) 
start_time = time.time()
total = np.sum(arr)
end_time = time.time()
elapsed_time_npsum = end_time - start_time
print("Tổng các phần tử mảng arr khi sử dụng hàm np.sum():", total) 
print("Thời gian (giây) khi sử dụng np.sum():", elapsed_time_npsum) 
num_times_faster = elapsed_time_loop / elapsed_time_npsum
print("Sử dụng vòng lặp chậm hơn: ~",int(num_times_faster),"lần")

Tổng các phần tử mảng arr khi sử dụng vòng lặp: 4999999950000000
Thời gian (giây) khi sử dụng vòng lặp: 15.197713851928711
Tổng các phần tử mảng arr khi sử dụng hàm np.sum(): 4999999950000000
Thời gian (giây) khi sử dụng np.sum(): 0.06805539131164551
Sử dụng vòng lặp chậm hơn: ~ 223 lần
